### ISSUE TITLE
Reuse ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());

### ISSUE THREAD

**Issue by pwrose** [rcsb/mmtf-java#19]
The MessagePack deserialization is slow. 

https://github.com/FasterXML/jackson-databind suggest to instantiate ObjectMapper once and then reuse it.

Try to instantiate:
ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());

once in the constructor and reuse it.

**Comment by abradle** [comment]
Made a PR.

This will not have an effect on Spark speed. As far as I can tell (from trying it - and it breaking) this is not threadsafe - so must still be constructed in each call function.  However it should make single threaded calculations faster.

As another point - my calculations showed it takes roughly 30 seconds to decode the Messagepacks for 120,000 or so. So that is the order of speed-up we would see. It's not tiny - but it's also not that significant.
